# Generated by Django 4.2.7 on 2025-05-07 00:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Historial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('tipo_entidad', models.CharField(choices=[('LIBRO', 'Libro'), ('PRESTAMO', 'Préstamo'), ('USUARIO', 'Usuario')], max_length=20)),
                ('tipo_accion', models.CharField(choices=[('CREACION', 'Creación'), ('MODIFICACION', 'Modificación'), ('ELIMINACION', 'Eliminación'), ('CAMBIO_ESTADO', 'Cambio de Estado')], max_length=20)),
                ('entidad_id', models.IntegerField()),
                ('detalles', models.TextField()),
                ('estado_anterior', models.CharField(blank=True, max_length=50, null=True)),
                ('estado_nuevo', models.CharField(blank=True, max_length=50, null=True)),
            ],
            options={
                'verbose_name': 'Registro de Historial',
                'verbose_name_plural': 'Registros de Historial',
                'db_table': 'historial',
                'ordering': ['-fecha'],
            },
        ),
    ]
