# Generated by Django 4.2.7 on 2025-05-07 00:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Libro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('autor', models.CharField(max_length=100)),
                ('editorial', models.CharField(max_length=100)),
                ('isbn', models.CharField(max_length=13, unique=True)),
                ('año_publicacion', models.IntegerField()),
                ('descripcion', models.TextField()),
                ('estado', models.CharField(choices=[('DISPONIBLE', 'Disponible'), ('PRESTADO', 'Prestado'), ('NO_DISPONIBLE', 'No Disponible')], default='DISPONIBLE', max_length=20)),
                ('cantidad_total', models.IntegerField(default=1)),
                ('cantidad_disponible', models.IntegerField(default=1)),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Libro',
                'verbose_name_plural': 'Libros',
                'db_table': 'libros',
                'ordering': ['titulo'],
            },
        ),
    ]
