# Generated by Django 4.2.7 on 2025-05-07 04:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('libros', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='libro',
            name='cantidad_disponible',
        ),
        migrations.RemoveField(
            model_name='libro',
            name='isbn',
        ),
        migrations.AlterField(
            model_name='libro',
            name='cantidad_total',
            field=models.IntegerField(default=1, verbose_name='Cantidad disponible para préstamo'),
        ),
    ]
