# Generated by Django 4.2.7 on 2025-05-08 01:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('prestamos', '0002_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='prestamo',
            options={'ordering': ['-fecha_aprobacion'], 'verbose_name': 'Préstamo', 'verbose_name_plural': 'Préstamos'},
        ),
    ]
